language: rust
rust:
  - nightly
script:
  - cargo build --release --all
  - cargo test --verbose --all

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH 
  file: target/release/filmow2letterboxd
  skip_cleanup: true
  on:
    branch: master
    tags: false