[package]
name = "filmow2letterboxd"
version = "0.1.0"
authors = ["Lucas Meireles"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.20"
select = "0.4.3"
csv = "1.1.3"
# log = "0.4.8"
