name: Tag Release 
run-name: Tagging latest release 🚀
on: 
  push:
    tags:
      - 'v*'

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}